"""Discrete and algebraic windows: graphs, set systems, designs, additive sets, SAT with RUP proofs, circuits, groups,
knots, polynomial algebra, curves over finite fields and exact geometry.

Every family is exact: witnesses are verified directly, values are computed by exhaustive or exact means within
stated bounds, and proofs are replayed step by step. Loaded by window_check.py, which passes its namespace as CORE.
"""
from fractions import Fraction as Q
from itertools import combinations, permutations, product
from math import comb, gcd, isqrt

core = CORE  # noqa: F821 (set by window_check before this module runs)
family, need, integer, Invalid = core.family, core.need, core.integer, core.Invalid
is_prime, factor, jacobi = core.is_prime, core.factor, core.jacobi


def _rat(x):
    if type(x) is int: return Q(x)
    need(type(x) is list and len(x) == 2 and all(type(v) is int for v in x) and x[1] > 0, 'rational pair')
    return Q(x[0], x[1])


# ------------------------------------------------------------- graphs

def _perm_group(gens, budget, limit=5000):
    """All elements of the permutation group generated by gens (tuples), by closure."""
    need(type(gens) is list and 1 <= len(gens) <= 6, 'generators')
    m = len(gens[0])
    gens = [tuple(g) for g in gens]
    need(all(sorted(g) == list(range(m)) for g in gens), 'permutations of 0..m-1')
    ident = tuple(range(m)); elems = {ident: 0}; order = [ident]; i = 0
    while i < len(order):
        g = order[i]; i += 1
        for s in gens:
            h = tuple(s[x] for x in g)
            if h not in elems:
                elems[h] = len(order); order.append(h); budget.use(m)
                need(len(order) <= limit, 'group order bound')
    return order, elems, gens


def graph_of(spec, budget):
    """(n, adjacency sets) of a graph given by edges or by name."""
    need(type(spec) is dict, 'graph')
    if 'edges' in spec:
        n = integer(spec['n'], 1, 2000); adj = [set() for _ in range(n)]
        for u, v in spec['edges']:
            need(type(u) is int and type(v) is int and 0 <= u < n and 0 <= v < n and u != v, 'edge')
            adj[u].add(v); adj[v].add(u)
        return n, adj
    name = spec.get('named')
    if name == 'petersen': return graph_of(dict(named='gp', n=5, k=2), budget)
    if name == 'gp':
        m, k = integer(spec['n'], 3, 500), integer(spec['k'], 1)
        need(k < m / 2, 'generalized Petersen parameter')
        edges = [[i, (i + 1) % m] for i in range(m)] + [[i, i + m] for i in range(m)] + \
                [[m + i, m + (i + k) % m] for i in range(m)]
        return graph_of(dict(n=2 * m, edges=edges), budget)
    if name == 'cycle':
        m = integer(spec['n'], 3, 2000); return graph_of(dict(n=m, edges=[[i, (i + 1) % m] for i in range(m)]), budget)
    if name == 'complete':
        m = integer(spec['n'], 1, 200); return graph_of(dict(n=m, edges=[list(e) for e in combinations(range(m), 2)]), budget)
    if name == 'paley':
        q = integer(spec['q'], 5, 2000); need(is_prime(q, budget) and q % 4 == 1, 'prime q = 1 mod 4')
        sq = {x * x % q for x in range(1, q)}
        return graph_of(dict(n=q, edges=[[i, j] for i, j in combinations(range(q), 2) if (j - i) % q in sq]), budget)
    if name == 'hypercube':
        d = integer(spec['d'], 1, 10)
        return graph_of(dict(n=1 << d, edges=[[v, v ^ (1 << b)] for v in range(1 << d) for b in range(d) if v < v ^ (1 << b)]), budget)
    if name == 'cayley':
        order, elems, gens = _perm_group(spec['perms'], budget)
        edges = set()
        for g in order:
            for s in gens:
                h = tuple(s[x] for x in g); a, b = elems[g], elems[h]
                if a != b: edges.add((min(a, b), max(a, b)))
        return graph_of(dict(n=len(order), edges=[list(e) for e in sorted(edges)]), budget)
    raise Invalid('unknown graph ' + str(name))


def _proper(adj, colors):
    return all(colors[u] != colors[v] for u in range(len(adj)) for v in adj[u])


def chromatic_number(n, adj, budget, cap=None):
    """Exact chromatic number by backtracking in DSATUR order."""
    best = [n + 1 if cap is None else cap + 1]
    colors = [-1] * n
    def pick():
        best_v, key = -1, None
        for v in range(n):
            if colors[v] < 0:
                sat = len({colors[u] for u in adj[v] if colors[u] >= 0})
                k = (sat, len(adj[v]))
                if key is None or k > key: best_v, key = v, k
        return best_v
    def go(used):
        budget.use(n)
        if used >= best[0]: return
        v = pick()
        if v < 0: best[0] = used; return
        banned = {colors[u] for u in adj[v]}
        for c in range(used + 1):
            if c in banned: continue
            if c == used and used + 1 >= best[0]: break
            colors[v] = c; go(max(used, c + 1)); colors[v] = -1
    go(0)
    return best[0]


@family('graph_q', 'coloring', 'witness',
        'The witness assigns one of k colors to each vertex of the graph so that adjacent vertices differ: the '
        'chromatic number is at most k.')
def fam_coloring(params, witness, budget):
    need(set(params) == {'graph', 'k'}, 'coloring fields'); k = integer(params['k'], 1, 1000)
    n, adj = graph_of(params['graph'], budget)
    need(type(witness) is list and len(witness) == n and all(type(c) is int and 0 <= c < k for c in witness), 'colors')
    budget.use(sum(len(a) for a in adj)); need(_proper(adj, witness), 'two adjacent vertices share a color')
    return dict(n=n, k=k)


@family('graph_q', 'chromatic', 'value', 'The chromatic number of the graph, by exhaustive backtracking.')
def fam_chromatic(params, budget):
    need(set(params) == {'graph'}, 'chromatic fields'); n, adj = graph_of(params['graph'], budget)
    need(n <= 120, 'graph size for exhaustive coloring')
    return chromatic_number(n, adj, budget)


@family('graph_q', 'ham_path', 'witness',
        'The witness lists every vertex once, each adjacent to the next: the graph has a Hamiltonian path.')
def fam_ham_path(params, witness, budget):
    need(set(params) == {'graph'}, 'path fields'); n, adj = graph_of(params['graph'], budget)
    need(type(witness) is list and sorted(witness) == list(range(n)), 'a permutation of the vertices')
    need(all(witness[i + 1] in adj[witness[i]] for i in range(n - 1)), 'consecutive vertices not adjacent')
    return dict(n=n)


def _free_trees(n, budget):
    """Every tree on n vertices up to isomorphism, as sorted edge lists with canonical codes (center-rooted AHU)."""
    out = {}
    # rooted trees as level sequences (Beyer-Hedetniemi), each read as a free tree and canonicalized
    def successor(L):
        # Beyer-Hedetniemi: p the last position above level 1, q its last possible parent before it; copy from q
        if not any(x > 1 for x in L): return None
        p = max(i for i in range(len(L)) if L[i] > 1)
        q = max(i for i in range(p) if L[i] == L[p] - 1)
        s = L[:p]
        for i in range(p, len(L)): s.append(s[i - (p - q)])
        return s
    L = list(range(n)) if n > 1 else [0]
    while L is not None:
        budget.use(n)
        edges = []; stack = []
        for i, lev in enumerate(L):
            while stack and L[stack[-1]] >= lev: stack.pop()
            if stack: edges.append((stack[-1], i))
            stack.append(i)
        code = tree_code(n, edges)
        if code not in out: out[code] = edges
        L = successor(L) if n > 2 else None
    return out


def tree_code(n, edges):
    adj = [[] for _ in range(n)]
    for u, v in edges: adj[u].append(v); adj[v].append(u)
    if n == 1: return '()'
    # centers by peeling leaves
    deg = [len(a) for a in adj]; leaves = [v for v in range(n) if deg[v] <= 1]; left = n
    while left > 2:
        nxt = []
        for v in leaves:
            left -= 1
            for u in adj[v]:
                deg[u] -= 1
                if deg[u] == 1: nxt.append(u)
        leaves = nxt
    def enc(v, parent):
        return '(' + ''.join(sorted(enc(u, v) for u in adj[v] if u != parent)) + ')'
    return min(enc(c, -1) for c in leaves)


def code_edges(code):
    """The rooted tree a parenthesis code describes, vertices numbered in preorder (the root is 0)."""
    edges = []; stack = []; count = 0
    for ch in code:
        if ch == '(':
            if stack: edges.append((stack[-1], count))
            stack.append(count); count += 1
        else: stack.pop()
    return edges


@family('graph_q', 'graceful_trees', 'witness',
        'Every tree with n vertices, up to isomorphism, has a graceful labeling: the witness gives for each tree, named '
        'by its canonical code (rooted at a center), labels 0..n-1 for its vertices in preorder of the code whose edge '
        'differences are 1..n-1.')
def fam_graceful_trees(params, witness, budget):
    need(set(params) == {'n'}, 'graceful fields'); n = integer(params['n'], 2, 16)
    trees = _free_trees(n, budget)
    need(type(witness) is dict and set(witness) == set(trees), 'one labeling for each tree')
    for code in trees:
        lab = witness[code]; budget.use(n); edges = code_edges(code)
        need(type(lab) is list and sorted(lab) == list(range(n)), 'labels 0..n-1')
        need(sorted(abs(lab[u] - lab[v]) for u, v in edges) == list(range(1, n)), 'not graceful: ' + code)
    return dict(trees=len(trees))


@family('graph_q', 'cycle_double_cover', 'witness',
        'The witness lists cycles of the graph covering every edge exactly twice.')
def fam_cdc(params, witness, budget):
    need(set(params) == {'graph'}, 'cover fields'); n, adj = graph_of(params['graph'], budget)
    need(type(witness) is list and witness, 'cycles'); count = {}
    for cyc in witness:
        need(type(cyc) is list and len(cyc) >= 3 and len(set(cyc)) == len(cyc), 'simple cycle')
        for i in range(len(cyc)):
            u, v = cyc[i], cyc[(i + 1) % len(cyc)]
            need(v in adj[u], 'not an edge'); e = (min(u, v), max(u, v)); count[e] = count.get(e, 0) + 1
    edges = {(u, v) for u in range(n) for v in adj[u] if u < v}
    need(set(count) == edges and all(c == 2 for c in count.values()), 'some edge is not covered exactly twice')
    return dict(cycles=len(witness))


def canonical_graph(n, edges, budget):
    """The lexicographically least adjacency string over vertex orders that sort vertices by degree."""
    adj = [[0] * n for _ in range(n)]; deg = [0] * n
    for u, v in edges: adj[u][v] = adj[v][u] = 1; deg[u] += 1; deg[v] += 1
    classes = {}
    for v in range(n): classes.setdefault(deg[v], []).append(v)
    groups = [classes[d] for d in sorted(classes)]
    best = None
    for parts in product(*[permutations(g) for g in groups]):
        order = [v for part in parts for v in part]; budget.use(n)
        s = ''.join(str(adj[order[i]][order[j]]) for i in range(n) for j in range(i + 1, n))
        if best is None or s < best: best = s
    return str(n) + ':' + best


def all_graphs(n, budget):
    """Every graph on n vertices up to isomorphism: {canonical code: edge list}."""
    pairs = list(combinations(range(n), 2)); out = {}
    for mask in range(1 << len(pairs)):
        edges = [pairs[i] for i in range(len(pairs)) if mask >> i & 1]
        code = canonical_graph(n, edges, budget)
        if code not in out: out[code] = edges
    return out


@family('graph_q', 'reconstruction', 'value',
        'For all graphs on n vertices up to isomorphism: their number, and whether their decks (multisets of '
        'vertex-deleted subgraphs up to isomorphism) are pairwise different.')
def fam_reconstruction(params, budget):
    need(set(params) == {'n'}, 'reconstruction fields'); n = integer(params['n'], 3, 6)
    graphs = all_graphs(n, budget); decks = set()
    for code, edges in graphs.items():
        deck = []
        for v in range(n):
            keep = [u for u in range(n) if u != v]; idx = {u: i for i, u in enumerate(keep)}
            sub = [(idx[a], idx[b]) for a, b in edges if a != v and b != v]
            deck.append(canonical_graph(n - 1, sub, budget))
        decks.add(tuple(sorted(deck)))
    return dict(graphs=len(graphs), distinct_decks=len(decks) == len(graphs))


def _oriented(n, budget):
    """Every oriented graph on n labeled vertices as out-neighbour sets (each pair: none, u -> v or v -> u)."""
    pairs = list(combinations(range(n), 2))
    for code in product((0, 1, 2), repeat=len(pairs)):
        budget.use(n)
        out = [set() for _ in range(n)]
        for (u, v), c in zip(pairs, code):
            if c == 1: out[u].add(v)
            elif c == 2: out[v].add(u)
        yield out


def _girth_directed(out, n):
    best = None
    for s in range(n):
        dist = {s: 0}; frontier = [s]
        while frontier:
            nxt = []
            for u in frontier:
                for v in out[u]:
                    if v == s:
                        L = dist[u] + 1; best = L if best is None or L < best else best
                    elif v not in dist: dist[v] = dist[u] + 1; nxt.append(v)
            frontier = nxt
    return best


@family('graph_q', 'oriented_census', 'value',
        'Over every oriented graph on n labeled vertices: how many violate the property (second_neighborhood: no '
        'vertex has at least as many vertices at distance 2 as at distance 1; caccetta: minimum out-degree r but no '
        'directed cycle of length at most ceil(n / r)).')
def fam_oriented(params, budget):
    need(set(params) == {'n', 'property', 'r'}, 'oriented fields'); n = integer(params['n'], 2, 5)
    prop, r = params['property'], integer(params['r'], 0, 4); bad = 0; checked = 0
    for out in _oriented(n, budget):
        if prop == 'second_neighborhood':
            checked += 1
            if not any(len({w for u in out[v] for w in out[u]} - out[v] - {v}) >= len(out[v]) for v in range(n)): bad += 1
        elif prop == 'caccetta':
            if min(len(o) for o in out) < r or r == 0: continue
            checked += 1; g = _girth_directed(out, n)
            if g is None or g > -(-n // r): bad += 1
        else: raise Invalid('unknown property')
    return dict(checked=checked, violations=bad)


def _has_cycle_length(n, adj, L, budget):
    """Whether the graph has a simple cycle of exactly L vertices (DFS from each least vertex)."""
    for s in range(n):
        stack = [(s, [s])]
        while stack:
            v, path = stack.pop(); budget.use()
            for u in adj[v]:
                if u == s and len(path) == L: return True
                if u > s and u not in path and len(path) < L: stack.append((u, path + [u]))
    return False


@family('graph_q', 'erdos_gyarfas_gp', 'value',
        'For every generalized Petersen graph GP(n, k) with 3 <= n <= n_max and 1 <= k < n/2 (cubic graphs): those '
        'without a cycle whose length is a power of 2 (the Erdos-Gyarfas conjecture says none).')
def fam_erdos_gyarfas(params, budget):
    need(set(params) == {'n_max'}, 'Erdos-Gyarfas fields'); N = integer(params['n_max'], 3, 16)
    fails = []
    for m in range(3, N + 1):
        for k in range(1, (m + 1) // 2):
            if 2 * k == m: continue
            n, adj = graph_of(dict(named='gp', n=m, k=k), budget)
            if not any(_has_cycle_length(n, adj, 1 << e, budget) for e in range(2, (2 * m).bit_length())): fails.append([m, k])
    return fails


@family('graph_q', 'total_coloring', 'witness',
        'The witness colors vertices and edges with at most D + 2 colors (D the maximum degree) so that adjacent '
        'vertices, incident edges and each edge and its ends all differ.')
def fam_total(params, witness, budget):
    need(set(params) == {'graph'}, 'total coloring fields'); n, adj = graph_of(params['graph'], budget)
    D = max(len(a) for a in adj); k = D + 2
    need(type(witness) is dict and set(witness) == {'vertices', 'edges'}, 'witness fields')
    vc, ec = witness['vertices'], witness['edges']
    need(type(vc) is list and len(vc) == n and all(type(c) is int and 0 <= c < k for c in vc), 'vertex colors')
    need(_proper(adj, vc), 'adjacent vertices share a color')
    edges = {(u, v) for u in range(n) for v in adj[u] if u < v}
    need(type(ec) is dict and set(ec) == {str(u) + '-' + str(v) for u, v in edges}, 'one color per edge')
    at = [set() for _ in range(n)]
    for (u, v) in edges:
        c = ec[str(u) + '-' + str(v)]; need(type(c) is int and 0 <= c < k, 'edge color')
        need(c not in at[u] and c not in at[v] and c != vc[u] and c != vc[v], 'a conflict at edge ' + str((u, v)))
        at[u].add(c); at[v].add(c)
    return dict(colors=k)


def chromatic_index(n, adj, budget):
    edges = sorted({(u, v) for u in range(n) for v in adj[u] if u < v}); D = max(len(a) for a in adj)
    inc = [[] for _ in range(n)]
    for i, (u, v) in enumerate(edges): inc[u].append(i); inc[v].append(i)
    for k in (D, D + 1):
        col = [-1] * len(edges)
        def go(i):
            budget.use()
            if i == len(edges): return True
            u, v = edges[i]; used = {col[j] for j in inc[u] + inc[v] if col[j] >= 0}
            for c in range(k):
                if c not in used:
                    col[i] = c
                    if go(i + 1): return True
            col[i] = -1; return False
        if go(0): return k
    raise Invalid('Vizing bound exceeded')


@family('graph_q', 'chromatic_index', 'value', 'The chromatic index of the graph (D or D + 1 by Vizing), by exhaustive search.')
def fam_chromatic_index(params, budget):
    need(set(params) == {'graph'}, 'edge coloring fields'); n, adj = graph_of(params['graph'], budget)
    need(sum(len(a) for a in adj) <= 120, 'edge count for exhaustive search')
    return chromatic_index(n, adj, budget)


@family('graph_q', 'srg_feasible', 'value',
        'The standard feasibility conditions for a strongly regular graph (v, k, lambda, mu): the counting identity, '
        'integral eigenvalue multiplicities, the Krein conditions and the absolute bound, each true or false.')
def fam_srg(params, budget):
    need(set(params) == {'v', 'k', 'l', 'm'}, 'SRG fields')
    v, k, l, m = (integer(params[x], 0, 10 ** 7) for x in ('v', 'k', 'l', 'm'))
    need(0 < k < v - 1, 'parameters')
    count = k * (k - l - 1) == (v - k - 1) * m
    D = (l - m) ** 2 + 4 * (k - m); rD = isqrt(D)
    out = dict(counting=count)
    # eigenvalues r, s = (l - m +- sqrt D) / 2 with multiplicities f, g
    num = 2 * k + (v - 1) * (l - m)
    if rD * rD == D:
        r2, s2 = (l - m) + rD, (l - m) - rD  # 2r, 2s
        f_num = (v - 1) * (-s2) - 2 * k; f_den = r2 - s2
        integral = f_den != 0 and f_num % f_den == 0
        out['multiplicities_integral'] = integral
        if integral:
            f = f_num // f_den; g = v - 1 - f; r, s = Q(r2, 2), Q(s2, 2)
            out['krein'] = ((r + 1) * (k + r + 2 * r * s) <= (k + r) * (s + 1) ** 2 and
                            (s + 1) * (k + s + 2 * r * s) <= (k + s) * (r + 1) ** 2)
            out['absolute_bound'] = v <= f * (f + 3) // 2 and v <= g * (g + 3) // 2
            out['eigenvalues'] = [str(r), str(s)]; out['multiplicities'] = [f, g]
    else:
        out['multiplicities_integral'] = num == 0 and (v - 1) % 2 == 0  # the conference case
        out['conference'] = num == 0
    return out


def _cliques(n, adj, s, budget):
    """Whether the graph has a clique of size s (Bron-Kerbosch with pivoting, stopping at s)."""
    found = [False]
    def bk(R, P, X):
        budget.use()
        if found[0]: return
        if len(R) >= s: found[0] = True; return
        if len(R) + len(P) < s: return
        pivot = max(P | X, key=lambda u: len(adj[u] & P)) if P | X else None
        for v in list(P - (adj[pivot] if pivot is not None else set())):
            bk(R | {v}, P & adj[v], X & adj[v]); P = P - {v}; X = X | {v}
            if found[0]: return
    bk(set(), set(range(n)), set())
    return found[0]


@family('graph_q', 'ramsey_coloring', 'witness',
        'The witness is a graph on n vertices (the edges of the first color) with no clique of size s and no '
        'independent set of size t: so R(s, t) > n.')
def fam_ramsey(params, witness, budget):
    need(set(params) == {'n', 's', 't'}, 'Ramsey fields')
    n, s, t = integer(params['n'], 2, 200), integer(params['s'], 2, 8), integer(params['t'], 2, 8)
    n2, adj = graph_of(dict(n=n, edges=witness), budget)
    comp = [set(range(n)) - adj[v] - {v} for v in range(n)]
    need(not _cliques(n, adj, s, budget), 'a clique of size s in the first color')
    need(not _cliques(n, comp, t, budget), 'a clique of size t in the second color')
    return dict(lower_bound=n + 1)


def _rooted_clique(n, adj, size, budget):
    """Whether a vertex-transitive graph (adjacency as bitmasks) has a clique of the size: by transitivity, one
    through vertex 0. Branch and bound; a greedy partition of the candidates into independent sets bounds the rest."""
    def bound(P):
        classes = 0
        while P:
            classes += 1; Q = P
            while Q:
                v = Q.bit_length() - 1; Q &= ~(1 << v); P &= ~(1 << v); Q &= ~adj[v]
        return classes
    def go(have, P):
        budget.use()
        if have >= size: return True
        if have + bin(P).count('1') < size or have + bound(P) < size: return False
        while P:
            v = P.bit_length() - 1; P &= ~(1 << v)
            if go(have + 1, P & adj[v]): return True
        return False
    return go(1, adj[0])


@family('graph_q', 'circulant_ramsey', 'witness',
        'The witness is the connection set of a circulant graph on n vertices (distances d, 1 <= d <= n/2, joining v '
        'to v + d and v - d) with no clique of size s and no independent set of size t, checked through vertex 0 by '
        'vertex transitivity: so R(s, t) > n.')
def fam_circulant_ramsey(params, witness, budget):
    need(set(params) == {'n', 's', 't'}, 'Ramsey fields')
    n, s, t = integer(params['n'], 3, 400), integer(params['s'], 3, 8), integer(params['t'], 3, 32)
    need(type(witness) is list and witness == sorted(set(witness)) and all(type(d) is int and 1 <= d <= n // 2 for d in witness),
         'distances 1..n/2, sorted, distinct')
    S = set(witness) | {n - d for d in witness}
    adj = [sum(1 << ((v + d) % n) for d in S) for v in range(n)]
    full = (1 << n) - 1
    comp = [full & ~adj[v] & ~(1 << v) for v in range(n)]
    need(not _rooted_clique(n, adj, s, budget), 'a clique of size s through vertex 0')
    need(not _rooted_clique(n, comp, t, budget), 'an independent set of size t through vertex 0')
    return dict(lower_bound=n + 1, degree=len(S))


def _hom_count(Hn, Hedges, n, adj, budget):
    """The number of homomorphisms from a small graph H into G."""
    order = list(range(Hn)); count = 0
    def go(i, phi):
        nonlocal count
        budget.use()
        if i == Hn: count += 1; return
        for x in range(n):
            if all((phi[j] in adj[x]) for j in range(i) if (j, i) in Hset or (i, j) in Hset):
                phi.append(x); go(i + 1, phi); phi.pop()
    Hset = {(min(a, b), max(a, b)) for a, b in Hedges}
    go(0, [])
    return count


@family('graph_q', 'sidorenko', 'value',
        'For the bipartite graph H and every graph G on n labeled vertices: the graphs G with hom(H, G) n^(2 e(H)) '
        '< (2 e(G))^(e(H)) n^(v(H)) (a counterexample to Sidorenko\'s inequality t(H, G) >= t(K2, G)^e(H)); their '
        'number and how many graphs were checked.')
def fam_sidorenko(params, budget):
    need(set(params) == {'H', 'n'}, 'Sidorenko fields'); n = integer(params['n'], 2, 5)
    H = params['H']; Hn, Hadj = graph_of(H, budget); Hedges = [(u, v) for u in range(Hn) for v in Hadj[u] if u < v]
    eH = len(Hedges); pairs = list(combinations(range(n), 2)); bad = 0; checked = 0
    for mask in range(1 << len(pairs)):
        edges = [pairs[i] for i in range(len(pairs)) if mask >> i & 1]
        _, adj = graph_of(dict(n=n, edges=[list(e) for e in edges]), budget); checked += 1
        if _hom_count(Hn, Hedges, n, adj, budget) * n ** (2 * eH) < (2 * len(edges)) ** eH * n ** Hn: bad += 1
    return dict(checked=checked, counterexamples=bad)


def _hadwiger(n, adj, budget):
    """The largest t such that K_t is a minor: branch sets as connected blocks of a set partition (small n)."""
    best = 1
    def partitions(items):
        if not items: yield []; return
        first, rest = items[0], items[1:]
        for p in partitions(rest):
            yield [[first]] + p
            for i in range(len(p)): yield p[:i] + [[first] + p[i]] + p[i + 1:]
    def connected(block):
        seen = {block[0]}; stack = [block[0]]; S = set(block)
        while stack:
            v = stack.pop()
            for u in adj[v] & S:
                if u not in seen: seen.add(u); stack.append(u)
        return len(seen) == len(S)
    for p in partitions(list(range(n))):
        budget.use(len(p))
        blocks = [b for b in p]
        # every block need not be used: take the connected blocks pairwise touching
        conn = [b for b in blocks if connected(b)]
        for size in range(len(conn), best, -1):
            for chosen in combinations(conn, size):
                if all(any(u in adj[v] for v in a for u in b) for a, b in combinations(chosen, 2)):
                    best = size; break
            if best >= size: break
    return best


@family('graph_q', 'hadwiger_small', 'value',
        'For every graph on n labeled vertices: how many have chromatic number above their Hadwiger number (the '
        'largest complete minor); Hadwiger\'s conjecture says none.')
def fam_hadwiger_small(params, budget):
    need(set(params) == {'n'}, 'Hadwiger fields'); n = integer(params['n'], 2, 5)
    pairs = list(combinations(range(n), 2)); bad = 0
    for mask in range(1 << len(pairs)):
        edges = [list(pairs[i]) for i in range(len(pairs)) if mask >> i & 1]
        _, adj = graph_of(dict(n=n, edges=edges), budget)
        if chromatic_number(n, adj, budget) > _hadwiger(n, adj, budget): bad += 1
    return dict(graphs=1 << len(pairs), violations=bad)


@family('graph_q', 'erdos_hajnal', 'value',
        'Over all graphs on n labeled vertices with no induced copy of H: the least value of max(clique number, '
        'independence number), with the number of such graphs.')
def fam_erdos_hajnal(params, budget):
    need(set(params) == {'H', 'n'}, 'Erdos-Hajnal fields'); n = integer(params['n'], 2, 6)
    Hn, Hadj = graph_of(params['H'], budget)
    Hcode = canonical_graph(Hn, [(u, v) for u in range(Hn) for v in Hadj[u] if u < v], budget)
    pairs = list(combinations(range(n), 2)); best = None; count = 0
    for mask in range(1 << len(pairs)):
        E = {pairs[i] for i in range(len(pairs)) if mask >> i & 1}
        induced = False
        for S in combinations(range(n), Hn):
            idx = {v: i for i, v in enumerate(S)}
            sub = [(idx[a], idx[b]) for a, b in combinations(S, 2) if (a, b) in E]
            budget.use()
            if canonical_graph(Hn, sub, budget) == Hcode: induced = True; break
        if induced: continue
        count += 1
        adj = [set() for _ in range(n)]
        for a, b in E: adj[a].add(b); adj[b].add(a)
        comp = [set(range(n)) - adj[v] - {v} for v in range(n)]
        w = max(s for s in range(1, n + 1) if _cliques(n, adj, s, budget) or s == 1)
        a_ = max(s for s in range(1, n + 1) if _cliques(n, comp, s, budget) or s == 1)
        m = max(w, a_); best = m if best is None or m < best else best
    return dict(graphs=count, least_max_clique_or_independent=best)


def pebbling_number(n, adj, budget, cap=40):
    """The least p such that every distribution of p pebbles can move a pebble to any target (moves take two
    pebbles off a vertex and put one on a neighbour)."""
    from functools import lru_cache
    for p in range(1, cap + 1):
        ok = True
        for target in range(n):
            @lru_cache(maxsize=None)
            def solvable(conf):
                budget.use()
                if conf[target] >= 1: return True
                for v in range(n):
                    if conf[v] >= 2:
                        for u in adj[v]:
                            c = list(conf); c[v] -= 2; c[u] += 1
                            if solvable(tuple(c)): return True
                return False
            def dists(k, i):
                if i == n - 1: yield (k,); return
                for a in range(k + 1):
                    for rest in dists(k - a, i + 1): yield (a,) + rest
            for conf in dists(p, 0):
                if not solvable(conf): ok = False; break
            if not ok: break
        if ok: return p
    raise Invalid('pebbling bound')


@family('graph_q', 'pebbling', 'value',
        'The pebbling numbers of G, H and their Cartesian product (small graphs), by exhaustive search over pebble '
        'distributions; Graham conjectured pi(G x H) <= pi(G) pi(H).')
def fam_pebbling(params, budget):
    need(set(params) == {'G', 'H'}, 'pebbling fields')
    gn, gadj = graph_of(params['G'], budget); hn, hadj = graph_of(params['H'], budget)
    need(gn * hn <= 9, 'product size')
    edges = []
    for a in range(gn):
        for b in range(hn):
            v = a * hn + b
            for a2 in gadj[a]: edges.append([v, a2 * hn + b])
            for b2 in hadj[b]: edges.append([v, a * hn + b2])
    pn, padj = graph_of(dict(n=gn * hn, edges=[e for e in edges if e[0] < e[1]]), budget)
    pg, ph, pp = pebbling_number(gn, gadj, budget), pebbling_number(hn, hadj, budget), pebbling_number(pn, padj, budget)
    return dict(G=pg, H=ph, product=pp, graham_holds=pp <= pg * ph)


@family('circuit_q', 'isomorphic', 'value',
        'Whether the two graphs (at most 64 vertices) are isomorphic: colour refinement separates most '
        'non-isomorphic pairs, and an exhaustive backtracking search over colour classes decides the rest.')
def fam_isomorphic(params, budget):
    need(set(params) == {'G', 'H'}, 'isomorphism fields')
    gn, gadj = graph_of(params['G'], budget); hn, hadj = graph_of(params['H'], budget)
    need(gn <= 64 and hn <= 64, 'graph size for the isomorphism search')
    if gn != hn or sum(map(len, gadj)) != sum(map(len, hadj)): return False
    n = gn
    # colour refinement on the disjoint union; different colour histograms mean non-isomorphic
    adj = [set(a) for a in gadj] + [{v + n for v in a} for a in hadj]
    colour = [len(a) for a in adj]
    while True:
        budget.use(2 * n)
        sig = [(colour[v], tuple(sorted(colour[u] for u in adj[v]))) for v in range(2 * n)]
        names = {k: i for i, k in enumerate(sorted(set(sig)))}
        new = [names[k] for k in sig]
        if len(set(new)) == len(set(colour)): colour = new; break
        colour = new
    if sorted(colour[:n]) != sorted(colour[n:]): return False
    # backtracking over colour classes, smallest classes first, keeping adjacency with mapped vertices
    order = sorted(range(n), key=lambda v: (sum(1 for u in range(n) if colour[u] == colour[v]), -len(gadj[v]), v))
    image = {}; used = set()
    def go(i):
        budget.use()
        if i == n: return True
        v = order[i]
        for w in range(n):
            if w in used or colour[w + n] != colour[v]: continue
            if all((u in gadj[v]) == (image[u] in hadj[w]) for u in image):
                image[v] = w; used.add(w)
                if go(i + 1): return True
                del image[v]; used.discard(w)
        return False
    return go(0)


# ------------------------------------------------------------- set systems

@family('setsys_q', 'frankl_small', 'value',
        'Every union-closed family of subsets of {1..m} with a nonempty member, enumerated: how many there are and '
        'how many have no element in at least half of their members.')
def fam_frankl(params, budget):
    need(set(params) == {'m'}, 'Frankl fields'); m = integer(params['m'], 1, 4)
    subsets = list(range(1 << m)); count = bad = 0
    for mask in range(1, 1 << (1 << m)):
        fam = [s for s in subsets if mask >> s & 1]; budget.use(len(fam))
        S = set(fam)
        if not all((a | b) in S for a in fam for b in fam): continue
        if not any(fam): continue
        count += 1
        if not any(2 * sum(1 for s in fam if s >> x & 1) >= len(fam) for x in range(m)): bad += 1
    return dict(families=count, counterexamples=bad)


def _is_sunflower(sets):
    core_ = set.intersection(*sets)
    return all((a & b) == core_ for a, b in combinations(sets, 2))


@family('setsys_q', 'sunflower_free', 'witness',
        'The witness is a family of distinct w-element sets with no k of them forming a sunflower (pairwise '
        'intersections all equal): a lower bound on the sunflower-free size.')
def fam_sunflower(params, witness, budget):
    need(set(params) == {'w', 'k', 'size'}, 'sunflower fields')
    w, k, size = integer(params['w'], 1, 6), integer(params['k'], 3, 5), integer(params['size'], 1, 200)
    need(type(witness) is list and len(witness) == size, 'family size')
    sets = [frozenset(s) for s in witness]
    need(all(len(s) == w for s in sets) and len(set(sets)) == size, 'distinct w-sets')
    for group in combinations(sets, k):
        budget.use(k)
        need(not _is_sunflower([set(g) for g in group]), 'a sunflower among the witness sets')
    return dict(size=size)


def _posets(n, budget):
    """Every partial order on n labeled elements as relation bitmasks (transitively closed DAGs)."""
    pairs = [(i, j) for i in range(n) for j in range(n) if i != j]
    def closed(rel):
        for (a, b) in rel:
            for (c, d) in rel:
                if b == c and (a, d) not in rel: return False
        return True
    out = []
    def go(i, rel):
        budget.use()
        if i == len(pairs):
            if closed(rel): out.append(frozenset(rel))
            return
        a, b = pairs[i]
        go(i + 1, rel)
        if (b, a) not in rel: go(i + 1, rel | {(a, b)})
    go(0, frozenset())
    return out


@family('setsys_q', 'balanced_pair', 'value',
        'Over every partial order on n labeled elements that is not a chain: the least, over the orders, of the largest '
        'balance min(p, 1 - p) of a pair, p the probability that x precedes y in a uniform linear extension (the '
        '1/3-2/3 conjecture says at least 1/3).')
def fam_balanced_pair(params, budget):
    need(set(params) == {'n'}, 'poset fields'); n = integer(params['n'], 2, 5)
    worst = None
    for rel in _posets(n, budget):
        below = [0] * n
        for a, b in rel: below[b] |= 1 << a
        # linear extensions counted by subsets; ext_before[x][y]: extensions with x before y
        cnt = {0: 1}
        for mask in range(1 << n):
            if mask not in cnt: continue
            for v in range(n):
                if not mask >> v & 1 and (below[v] & ~mask) == 0:
                    cnt[mask | 1 << v] = cnt.get(mask | 1 << v, 0) + cnt[mask]
        total = cnt.get((1 << n) - 1, 0)
        incomparable = [(x, y) for x, y in combinations(range(n), 2) if (x, y) not in rel and (y, x) not in rel]
        if not incomparable: continue
        best = Q(0)
        for x, y in incomparable:
            # extensions with x before y: count linear extensions of rel + (x, y)
            b2 = list(below); b2[y] |= 1 << x
            c2 = {0: 1}
            for mask in range(1 << n):
                if mask not in c2: continue
                for v in range(n):
                    if not mask >> v & 1 and (b2[v] & ~mask) == 0:
                        c2[mask | 1 << v] = c2.get(mask | 1 << v, 0) + c2[mask]
            p = Q(c2.get((1 << n) - 1, 0), total); budget.use(1 << n)
            best = max(best, min(p, 1 - p))
        worst = best if worst is None or best < worst else worst
    return [worst.numerator, worst.denominator]


@family('setsys_q', 'rota_f2', 'value',
        'For every ordered triple of bases of F_2^3: whether its nine vectors fit a 3 x 3 grid whose rows are the bases '
        'and whose columns are also bases (Rota\'s basis conjecture for n = 3 over F_2); the number of failures.')
def fam_rota(params, budget):
    need(set(params) == {'n'}, 'Rota fields'); integer(params['n'], 3, 3)
    vecs = list(range(1, 8))
    def indep(a, b, c): return a != b and c not in (a, b, a ^ b) and c != 0
    bases = [B for B in combinations(vecs, 3) if indep(*B)]; fails = 0
    for B1 in bases:
        for B2 in bases:
            for B3 in bases:
                budget.use(36)
                if not any(all(indep(B1[j], p2[j], p3[j]) for j in range(3))
                           for p2 in permutations(B2) for p3 in permutations(B3)): fails += 1
    return dict(triples=len(bases) ** 3, failures=fails)


# ------------------------------------------------------------- additive combinatorics

@family('additive_q', 'prime_ap', 'witness',
        'The witness [a, d] gives k primes a, a + d, ..., a + (k-1) d in arithmetic progression.')
def fam_prime_ap(params, witness, budget):
    need(set(params) == {'k'}, 'progression fields'); k = integer(params['k'], 2, 30)
    need(type(witness) is list and len(witness) == 2, 'start and difference'); a, d = witness
    integer(a, 2); integer(d, 1)
    need(all(is_prime(a + i * d, budget) for i in range(k)), 'a term is not prime')
    return dict(k=k)


def _sidon(S):
    sums = set()
    for i, a in enumerate(S):
        for b in S[i:]:
            if a + b in sums: return False
            sums.add(a + b)
    return True


@family('additive_q', 'sidon_set', 'witness',
        'The witness is a subset of {1..n} of the stated size whose pairwise sums (with repetition) are distinct.')
def fam_sidon_set(params, witness, budget):
    need(set(params) == {'n', 'size'}, 'Sidon fields'); n, size = integer(params['n'], 1, 10 ** 6), integer(params['size'], 1)
    need(type(witness) is list and len(witness) == size and len(set(witness)) == size
         and all(type(x) is int and 1 <= x <= n for x in witness), 'distinct elements of 1..n')
    budget.use(size * size); need(_sidon(sorted(witness)), 'two pairs share a sum')
    return dict(size=size)


@family('additive_q', 'sidon_max', 'value', 'The largest size of a Sidon subset of {1..n}, by exhaustive search.')
def fam_sidon_max(params, budget):
    need(set(params) == {'n'}, 'Sidon fields'); n = integer(params['n'], 1, 60)
    best = [0]
    def go(x, S, diffs):
        budget.use()
        if len(S) + (n - x + 1) <= best[0]: return
        if len(S) > best[0]: best[0] = len(S)
        for y in range(x, n + 1):
            nd = {y - s for s in S}
            if len(nd) == len(S) and not nd & diffs:
                go(y + 1, S + [y], diffs | nd)
    go(1, [], set())
    return best[0]


WAERDEN_ALPHABET = '0123456789abcdefghijklmnopqrstuv'


@family('additive_q', 'waerden_coloring', 'witness',
        'The witness colors 1..n with r colors (one letter per number) so that no k-term arithmetic progression is '
        'monochromatic: so the van der Waerden number W(r, k) exceeds n.')
def fam_waerden(params, witness, budget):
    need(set(params) == {'n', 'r', 'k'}, 'van der Waerden fields')
    n, r, k = integer(params['n'], 1, 20000), integer(params['r'], 2, 32), integer(params['k'], 3, 8)
    need(type(witness) is str and len(witness) == n and set(witness) <= set(WAERDEN_ALPHABET[:r]), 'a color letter per number')
    for d in range(1, (n - 1) // (k - 1) + 1):
        budget.use(n)
        rows = zip(*(witness[i * d:] for i in range(k)))
        for a, row in enumerate(rows):
            need(any(c != row[0] for c in row), 'a monochromatic progression at %d with step %d' % (a + 1, d))
    return dict(lower_bound=n + 1, colors=r, length=k)


@family('additive_q', 'four_cubes', 'value',
        'The numbers below N that are not sums of four positive cubes: how many, the largest, and the last few.')
def fam_four_cubes(params, budget):
    need(set(params) == {'N'}, 'cube fields'); N = integer(params['N'], 10, 5_000_000)
    need(N <= 1_000_000, 'cube range')
    cubes = [c ** 3 for c in range(1, int(round(N ** (1 / 3))) + 2) if c ** 3 < N]
    sums = sorted({a + b for a in cubes for b in cubes if a + b < N}); two = 0
    for t in sums: two |= 1 << t
    four = 0; budget.use(len(sums) * (N // 4096 + 1))
    for t in sums: four |= two << t
    four &= (1 << N) - 1
    missing = [n for n in range(1, N) if not four >> n & 1]
    return dict(count=len(missing), largest=missing[-1] if missing else None, last=missing[-12:])


@family('additive_q', 'representation_max', 'value',
        'For the basis B = E + O-style set of numbers whose binary digits all sit in even positions or all in odd '
        'positions: the largest number of representations n = a + b (a <= b in B) over n <= N, and where.')
def fam_representation(params, budget):
    need(set(params) == {'N'}, 'basis fields'); N = integer(params['N'], 1, 200_000)
    evens = 0x5555555555555555555555; odds = evens << 1
    B = [x for x in range(N + 1) if (x & odds) == 0 or (x & evens) == 0]
    Bset = set(B); best = (0, 0)
    for n in range(N + 1):
        r = 0
        for a in B:
            if 2 * a > n: break
            if n - a in Bset: r += 1
        budget.use(len(B) // 8 + 1)
        if r > best[0]: best = (r, n)
    return dict(max_representations=best[0], at=best[1])


@family('additive_q', 'sum_product', 'value',
        'For the named n-element set of integers: |A + A| and |A A| exactly.')
def fam_sum_product(params, budget):
    need(set(params) == {'kind', 'n'}, 'sum-product fields'); n = integer(params['n'], 1, 3000)
    kind = params['kind']
    A = dict(ap=lambda: list(range(1, n + 1)), gp=lambda: [2 ** i for i in range(n)],
             squares=lambda: [i * i for i in range(1, n + 1)],
             primes=lambda: [p for p in range(2, 40 * n) if is_prime(p, budget)][:n])[kind]()
    budget.use(n * n)
    return dict(sums=len({a + b for a in A for b in A}), products=len({a * b for a in A for b in A}), n=n)


# ------------------------------------------------------------- designs

def _prime_power(q):
    if q < 2: return None
    f = factor(q, _NB)
    return (next(iter(f)), next(iter(f.values()))) if len(f) == 1 else None


class _NB:
    @staticmethod
    def use(n=1): pass


@family('design_q', 'hadamard', 'witness',
        'The witness rows of + and - form an n x n Hadamard matrix: H H^T = n I.')
def fam_hadamard(params, witness, budget):
    need(set(params) == {'n'}, 'Hadamard fields'); n = integer(params['n'], 1, 2000)
    need(type(witness) is list and len(witness) == n and all(type(r) is str and len(r) == n and set(r) <= {'+', '-'}
                                                             for r in witness), 'rows of + and -')
    rows = [int(r.replace('+', '1').replace('-', '0'), 2) for r in witness]
    for i in range(n):
        for j in range(i + 1, n):
            budget.use(n // 64 + 1)
            need(bin(rows[i] ^ rows[j]).count('1') * 2 == n, 'rows ' + str(i) + ' and ' + str(j) + ' are not orthogonal')
    return dict(n=n)


def hadamard_constructible(k_max):
    """Orders 4k <= 4 k_max reached from 1 and 2 by Sylvester doubling, Paley I (q + 1, q = 3 mod 4 a prime power),
    Paley II (2(q + 1), q = 1 mod 4) and Kronecker products."""
    top = 4 * k_max; have = {1, 2}
    for q in range(2, top + 1):
        pp = _prime_power(q)
        if pp and q % 4 == 3 and q + 1 <= top: have.add(q + 1)
        if pp and q % 4 == 1 and 2 * (q + 1) <= top: have.add(2 * (q + 1))
    changed = True
    while changed:
        changed = False
        for a in sorted(have):
            for b in sorted(have):
                if a * b <= top and a * b not in have: have.add(a * b); changed = True
    return have


@family('design_q', 'hadamard_orders', 'value',
        'The orders 4k <= 4 k_max that Sylvester doubling, the two Paley constructions and Kronecker products do not '
        'reach (the Hadamard conjecture says every 4k is an order).')
def fam_hadamard_orders(params, budget):
    need(set(params) == {'k_max'}, 'order fields'); K = integer(params['k_max'], 1, 2000); budget.use(K * 8)
    have = hadamard_constructible(K)
    return [4 * k for k in range(1, K + 1) if 4 * k not in have]


@family('design_q', 'projective_plane', 'witness',
        'The witness lines (lists of point indices) form a projective plane of order q: q^2 + q + 1 points and '
        'lines, q + 1 points on each line, and every two points on exactly one line.')
def fam_plane(params, witness, budget):
    need(set(params) == {'q'}, 'plane fields'); q = integer(params['q'], 2, 40); N = q * q + q + 1
    need(type(witness) is list and len(witness) == N, 'line count')
    seen = {}
    for li, line in enumerate(witness):
        need(type(line) is list and len(line) == q + 1 and len(set(line)) == q + 1
             and all(type(p) is int and 0 <= p < N for p in line), 'line shape')
        for a, b in combinations(sorted(line), 2):
            budget.use(); need((a, b) not in seen, 'two points on two lines'); seen[(a, b)] = li
    need(len(seen) == N * (N - 1) // 2, 'some pair of points on no line')
    return dict(order=q)


@family('design_q', 'plane_orders', 'value',
        'For each order n <= n_max: constructible (a prime power, from a finite field), excluded (Bruck-Ryser: n = 1 or '
        '2 mod 4 and not a sum of two squares), or unknown to these two rules.')
def fam_plane_orders(params, budget):
    need(set(params) == {'n_max'}, 'order fields'); N = integer(params['n_max'], 2, 10_000)
    out = {}
    for n in range(2, N + 1):
        budget.use()
        if _prime_power(n): out[str(n)] = 'constructible'
        elif n % 4 in (1, 2) and not any(isqrt(n - a * a) ** 2 == n - a * a for a in range(isqrt(n) + 1)):
            out[str(n)] = 'excluded'
        else: out[str(n)] = 'unknown'
    return out


@family('design_q', 'mols', 'witness',
        'The witness gives k Latin squares of order n (rows of symbols 0..n-1), pairwise orthogonal.')
def fam_mols(params, witness, budget):
    need(set(params) == {'n', 'k'}, 'MOLS fields'); n, k = integer(params['n'], 2, 30), integer(params['k'], 1, 29)
    need(type(witness) is list and len(witness) == k, 'square count')
    for L in witness:
        need(type(L) is list and len(L) == n and all(type(r) is list and sorted(r) == list(range(n)) for r in L), 'rows')
        need(all(sorted(L[i][j] for i in range(n)) == list(range(n)) for j in range(n)), 'columns')
    for A, B in combinations(witness, 2):
        budget.use(n * n)
        need(len({(A[i][j], B[i][j]) for i in range(n) for j in range(n)}) == n * n, 'two squares are not orthogonal')
    return dict(n=n, k=k)


# ------------------------------------------------------------- SAT with RUP proofs

def cnf_of(encoder, params):
    """(number of variables, clauses) of a named finite question; variables are 1..V, literals signed."""
    need(type(params) is dict, 'encoder parameters')
    if encoder == 'php':
        n = integer(params['n'], 1, 12); P, H = n + 1, n
        v = lambda p, h: p * H + h + 1
        clauses = [[v(p, h) for h in range(H)] for p in range(P)]
        clauses += [[-v(p, h), -v(q, h)] for h in range(H) for p, q in combinations(range(P), 2)]
        return P * H, clauses
    if encoder == 'ramsey':
        n, s, t = integer(params['n'], 2, 40), integer(params['s'], 2, 6), integer(params['t'], 2, 6)
        idx = {e: i + 1 for i, e in enumerate(combinations(range(n), 2))}
        clauses = [[-idx[e] for e in combinations(S, 2)] for S in combinations(range(n), s)]
        clauses += [[idx[e] for e in combinations(S, 2)] for S in combinations(range(n), t)]
        return len(idx), clauses
    if encoder == 'schur':
        n, k = integer(params['n'], 1, 200), integer(params['k'], 1, 6)
        v = lambda i, c: (i - 1) * k + c + 1
        clauses = [[v(i, c) for c in range(k)] for i in range(1, n + 1)]
        clauses += [[-v(i, c), -v(j, c), -v(i + j, c)] for c in range(k) for i in range(1, n + 1)
                    for j in range(i, n + 1 - i)]
        return n * k, clauses
    if encoder == 'waerden':
        n, L = integer(params['n'], 1, 200), integer(params['k'], 2, 10)
        clauses = []
        for a in range(1, n + 1):
            for d in range(1, n):
                if a + (L - 1) * d > n: break
                terms = [a + i * d for i in range(L)]
                clauses.append(terms); clauses.append([-x for x in terms])
        return n, clauses
    raise Invalid('unknown encoder ' + str(encoder))


@family('sat_q', 'sat', 'witness',
        'The witness assignment satisfies every clause of the named question\'s CNF encoding: the question has a '
        'solution (for ramsey: a coloring of K_n with no K_s in the first color and no K_t in the second; for schur: a '
        'partition of 1..n into k sum-free parts; for waerden: a 2-coloring of 1..n without a monochromatic k-term '
        'progression).')
def fam_sat(params, witness, budget):
    need(set(params) == {'encoder', 'args'}, 'SAT fields'); V, clauses = cnf_of(params['encoder'], params['args'])
    need(type(witness) is str and len(witness) == V and set(witness) <= {'0', '1'}, 'a 0/1 string per variable')
    val = lambda lit: (witness[abs(lit) - 1] == '1') == (lit > 0)
    for c in clauses:
        budget.use(len(c)); need(any(val(l) for l in c), 'an unsatisfied clause')
    return dict(variables=V, clauses=len(clauses))


def rup_check(V, clauses, lemmas, budget):
    """Each lemma must follow from the clauses and earlier lemmas by unit propagation (its negation propagates to a
    conflict); the last lemma must be empty. Watched-literal propagation."""
    need(type(lemmas) is list and lemmas and lemmas[-1] == [], 'the proof must end with the empty clause')
    # a repeated literal would be watched twice and hide the clause's other watch: clauses are sets of literals
    db = [list(dict.fromkeys(c)) for c in clauses]; watches = {}
    def add(c):
        i = len(db) - 1
        for lit in c[:2]: watches.setdefault(lit, []).append(i)
    for i, c in enumerate(db):
        for lit in c[:2]: watches.setdefault(lit, []).append(i)
    def propagate(assign):
        # assign: dict var -> bool; returns True on conflict
        queue = [l for l in assign_lits]
        units = [c for c in db if len(c) == 1]
        for c in units:
            lit = c[0]; v = assign.get(abs(lit))
            if v is None: assign[abs(lit)] = lit > 0; queue.append(lit)
            elif v != (lit > 0): return True
        while queue:
            lit = queue.pop(); budget.use()
            neg = -lit
            for i in list(watches.get(neg, [])):
                c = db[i]
                if len(c) == 1: continue
                if c[0] == neg: c[0], c[1] = c[1], c[0]
                if c[1] != neg: continue
                first = c[0]; fv = assign.get(abs(first))
                if fv is not None and fv == (first > 0): continue
                moved = False
                for k in range(2, len(c)):
                    x = c[k]; xv = assign.get(abs(x))
                    if xv is None or xv == (x > 0):
                        c[1], c[k] = c[k], c[1]
                        watches[neg].remove(i); watches.setdefault(c[1], []).append(i); moved = True; break
                if moved: continue
                if fv is None: assign[abs(first)] = first > 0; queue.append(first)
                else: return True
        return False
    for lemma in lemmas:
        need(type(lemma) is list and all(type(l) is int and l != 0 and abs(l) <= V for l in lemma), 'lemma literals')
        assign = {}; assign_lits = []
        conflict = False
        for l in lemma:
            v = assign.get(abs(l))
            if v is None: assign[abs(l)] = l < 0; assign_lits.append(-l)
            elif v != (l < 0): conflict = True
        if not conflict: conflict = propagate(assign)
        need(conflict, 'a lemma is not implied by unit propagation')
        if lemma:
            db.append(list(dict.fromkeys(lemma)))
            for lit in db[-1][:2]: watches.setdefault(lit, []).append(len(db) - 1)
    return len(lemmas)


@family('sat_q', 'unsat', 'proof',
        'The named question\'s CNF encoding has no solution: the proof is a list of clauses, each implied by unit '
        'propagation from the encoding and the clauses before it (RUP), ending with the empty clause.')
def fam_unsat(params, proof, budget):
    need(set(params) == {'encoder', 'args'}, 'SAT fields'); V, clauses = cnf_of(params['encoder'], params['args'])
    need(len(proof) <= 200_000, 'proof length')
    return dict(lemmas=rup_check(V, clauses, proof, budget), variables=V, clauses=len(clauses))


# ------------------------------------------------------------- Boolean circuits

def _gate(op, a, b):
    """Binary gate op in 0..15: bit (2x + y) of op is the output on inputs (x, y); tables are bit-sliced ints."""
    return ((op >> 0 & 1) * (~a & ~b)) | ((op >> 1 & 1) * (~a & b)) | ((op >> 2 & 1) * (a & ~b)) | ((op >> 3 & 1) * (a & b))


def _inputs(n):
    size = 1 << n; mask = (1 << size) - 1
    return [sum(1 << r for r in range(size) if r >> (n - 1 - i) & 1) for i in range(n)], mask


@family('circuit_q', 'circuit', 'witness',
        'The witness gates [op, i, j] (op a binary Boolean function 0..15 on earlier wires, inputs first) compute the '
        'n-input function with the given truth table at the last gate: its circuit size is at most the gate count.')
def fam_circuit(params, witness, budget):
    need(set(params) == {'n', 'table', 'size'}, 'circuit fields')
    n, size = integer(params['n'], 1, 6), integer(params['size'], 0, 64); table = integer(params['table'], 0, (1 << (1 << n)) - 1)
    need(type(witness) is list and len(witness) <= size, 'gate count')
    wires, mask = _inputs(n)
    for g in witness:
        need(type(g) is list and len(g) == 3 and all(type(x) is int for x in g) and 0 <= g[0] <= 15
             and 0 <= g[1] < len(wires) and 0 <= g[2] < len(wires), 'gate')
        wires.append(_gate(g[0], wires[g[1]], wires[g[2]]) & mask); budget.use()
    need(wires[-1] == table if witness else table in wires, 'the circuit computes another function')
    return dict(gates=len(witness))


@family('circuit_q', 'circuit_sizes', 'value',
        'For every Boolean function of n inputs (n <= 3): the least number of binary gates computing it when that is at '
        'most max_size, by exhaustive search over circuits (sets of computed functions); the number of functions of '
        'each size, and how many need more than max_size gates (a proved lower bound).')
def fam_circuit_sizes(params, budget):
    need(set(params) == {'n', 'max_size'}, 'circuit size fields')
    n, S = integer(params['n'], 1, 3), integer(params['max_size'], 1, 3)
    ins, mask = _inputs(n); total = 1 << (1 << n)
    found = {t: 0 for t in ins}; frontier = {frozenset(ins)}
    for size in range(1, S + 1):
        nxt = set(); last = size == S
        for wires in frontier:
            ws = sorted(wires)
            for i, a in enumerate(ws):
                for b in ws[i:]:
                    for op in range(16):
                        budget.use()
                        t = _gate(op, a, b) & mask
                        if t in wires: continue
                        if t not in found: found[t] = size
                        if not last: nxt.add(wires | {t})
        frontier = nxt
        need(len(frontier) <= 300_000, 'search frontier bound')
    hist = {}
    for t, s in found.items(): hist[str(s)] = hist.get(str(s), 0) + 1
    hist = dict(sorted(hist.items(), key=lambda kv: int(kv[0])))
    hist['more'] = total - len(found)
    return hist


@family('circuit_q', 'unique_game', 'value',
        'For the unique game on the listed constraint graph (each edge a permutation of k labels): the largest fraction '
        'of constraints a labeling satisfies, by exhaustive search.')
def fam_unique_game(params, budget):
    need(set(params) == {'n', 'k', 'constraints'}, 'unique game fields')
    n, k = integer(params['n'], 1, 10), integer(params['k'], 2, 4); cs = params['constraints']
    need(type(cs) is list and cs and k ** n <= 1_100_000, 'instance size')
    for c in cs: need(type(c) is list and len(c) == 3 and sorted(c[2]) == list(range(k)), 'constraint [u, v, permutation]')
    best = 0
    for lab in product(range(k), repeat=n):
        budget.use(len(cs)); s = sum(1 for u, v, pi in cs if pi[lab[u]] == lab[v])
        if s > best: best = s
    return [best, len(cs)]


# ------------------------------------------------------------- exact geometry

def _pt(p, dim=2):
    need(type(p) is list and len(p) == dim, 'point'); return tuple(_rat(x) for x in p)


def _d2(a, b): return sum((x - y) ** 2 for x, y in zip(a, b))


def _is_square_q(q):
    q = Q(q)
    return q >= 0 and isqrt(q.numerator) ** 2 == q.numerator and isqrt(q.denominator) ** 2 == q.denominator


def _area2(a, b, c): return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])


@family('config_q', 'unit_distances', 'witness',
        'The witness is a set of n distinct rational points in the plane with at least count pairs at distance exactly '
        '1: so u(n) >= count.')
def fam_unit_distances(params, witness, budget):
    need(set(params) == {'n', 'count'}, 'unit distance fields'); n, c = integer(params['n'], 2, 3000), integer(params['count'], 0)
    need(type(witness) is list and len(witness) == n, 'point count'); P = [_pt(p) for p in witness]
    need(len(set(P)) == n, 'distinct points')
    u = 0
    for a, b in combinations(P, 2):
        budget.use()
        if _d2(a, b) == 1: u += 1
    need(u >= c, 'fewer unit distances than claimed')
    return dict(unit_distances=u)


@family('config_q', 'heilbronn', 'witness',
        'The witness places n points in the unit square with every triangle of area at least the stated value: a '
        'lower bound for Heilbronn\'s problem.')
def fam_heilbronn(params, witness, budget):
    need(set(params) == {'n', 'area'}, 'Heilbronn fields'); n = integer(params['n'], 3, 40); A = _rat(params['area'])
    need(type(witness) is list and len(witness) == n, 'point count'); P = [_pt(p) for p in witness]
    need(all(0 <= x <= 1 and 0 <= y <= 1 for x, y in P), 'points in the unit square')
    for a, b, c in combinations(P, 3):
        budget.use(); need(abs(_area2(a, b, c)) >= 2 * A, 'a triangle smaller than claimed')
    return dict(n=n)


@family('config_q', 'no_three_in_line', 'witness',
        'The witness gives 2n points of the n x n grid with no three on a line.')
def fam_no_three(params, witness, budget):
    need(set(params) == {'n'}, 'grid fields'); n = integer(params['n'], 1, 64)
    need(type(witness) is list and len(witness) == 2 * n and len({tuple(p) for p in witness}) == 2 * n
         and all(type(p) is list and len(p) == 2 and all(type(v) is int and 0 <= v < n for v in p) for p in witness),
         '2n distinct grid points')
    for a, b, c in combinations(witness, 3):
        budget.use(); need(_area2(a, b, c) != 0, 'three collinear points')
    return dict(points=2 * n)


def _convex_position(pts):
    """Whether the points are in strictly convex position (each a vertex of the hull)."""
    n = len(pts)
    for i in range(n):
        for j in range(n):
            if i == j: continue
            side = [_area2(pts[i], pts[j], pts[k]) for k in range(n) if k not in (i, j)]
            if all(s > 0 for s in side) or all(s < 0 for s in side): break
        else:
            return False
    return True


@family('config_q', 'convex_free', 'witness',
        'The witness gives n points in general position (no three collinear) with no k of them in convex position: so '
        'the Erdos-Szekeres number for k exceeds n.')
def fam_convex_free(params, witness, budget):
    need(set(params) == {'n', 'k'}, 'convex fields'); n, k = integer(params['n'], 3, 40), integer(params['k'], 3, 8)
    need(type(witness) is list and len(witness) == n, 'point count'); P = [_pt(p) for p in witness]
    for a, b, c in combinations(P, 3):
        budget.use(); need(_area2(a, b, c) != 0, 'three collinear points')
    for S in combinations(P, k):
        budget.use(k * k); need(not _convex_position(list(S)), 'a convex ' + str(k) + '-gon')
    return dict(n=n, k=k)


@family('config_q', 'kissing', 'witness',
        'The witness gives count integer vectors in dimension dim, all of the same squared length N, with pairwise inner '
        'products at most N/2: unit spheres centered at them (scaled) all touch a central one without overlapping, so '
        'the kissing number in this dimension is at least count.')
def fam_kissing(params, witness, budget):
    need(set(params) == {'dim', 'count'}, 'kissing fields'); d, c = integer(params['dim'], 1, 24), integer(params['count'], 1)
    need(type(witness) is list and len(witness) == c and all(type(v) is list and len(v) == d and all(type(x) is int for x in v)
                                                             for v in witness), 'integer vectors')
    N = sum(x * x for x in witness[0]); need(N > 0 and all(sum(x * x for x in v) == N for v in witness), 'equal lengths')
    for u, v in combinations(witness, 2):
        budget.use(d); need(2 * sum(a * b for a, b in zip(u, v)) <= N, 'two vectors closer than 60 degrees')
    return dict(count=c)


@family('config_q', 'rational_distances', 'witness',
        'The witness gives n rational points in the plane, no three on a line and no four on a circle, with every '
        'pairwise distance rational.')
def fam_rational_distances(params, witness, budget):
    need(set(params) == {'n'}, 'rational distance fields'); n = integer(params['n'], 2, 40)
    need(type(witness) is list and len(witness) == n, 'point count'); P = [_pt(p) for p in witness]
    for a, b in combinations(P, 2): budget.use(); need(_is_square_q(_d2(a, b)), 'an irrational distance')
    for a, b, c in combinations(P, 3): need(_area2(a, b, c) != 0, 'three collinear points')
    for a, b, c, d in combinations(P, 4):
        budget.use()
        # concyclic test: the lifted determinant vanishes
        rows = [[p[0] - d[0], p[1] - d[1], (p[0] - d[0]) ** 2 + (p[1] - d[1]) ** 2] for p in (a, b, c)]
        det = (rows[0][0] * (rows[1][1] * rows[2][2] - rows[1][2] * rows[2][1]) - rows[0][1] * (rows[1][0] * rows[2][2] -
               rows[1][2] * rows[2][0]) + rows[0][2] * (rows[1][0] * rows[2][1] - rows[1][1] * rows[2][0]))
        need(det != 0, 'four concyclic points')
    return dict(n=n)


class QF:
    """Elements of a multiquadratic field Q(sqrt a, sqrt b): coefficients of 1, sqrt a, sqrt b, sqrt(ab)."""
    __slots__ = ('c', 'a', 'b')

    def __init__(self, c, a, b): self.c, self.a, self.b = tuple(Q(x) for x in c), a, b

    def __add__(self, o): return QF([x + y for x, y in zip(self.c, o.c)], self.a, self.b)

    def __sub__(self, o): return QF([x - y for x, y in zip(self.c, o.c)], self.a, self.b)

    def __mul__(self, o):
        a, b = self.a, self.b; x, y = self.c, o.c
        return QF([x[0] * y[0] + a * x[1] * y[1] + b * x[2] * y[2] + a * b * x[3] * y[3],
                   x[0] * y[1] + x[1] * y[0] + b * (x[2] * y[3] + x[3] * y[2]),
                   x[0] * y[2] + x[2] * y[0] + a * (x[1] * y[3] + x[3] * y[1]),
                   x[0] * y[3] + x[3] * y[0] + x[1] * y[2] + x[2] * y[1]], a, b)

    def is_one(self): return self.c == (1, 0, 0, 0)


@family('config_q', 'unit_distance_graph', 'witness',
        'The witness places points in the plane with coordinates in Q(sqrt a, sqrt b) and lists edges between points at '
        'distance exactly 1 (checked in the field); the graph is not colorable with colors - 1 colors, so the '
        'chromatic number of the plane is at least colors.')
def fam_unit_distance_graph(params, witness, budget):
    need(set(params) == {'a', 'b', 'colors'}, 'unit distance graph fields')
    a, b, k = integer(params['a'], 2, 1000), integer(params['b'], 2, 1000), integer(params['colors'], 2, 6)
    need(type(witness) is dict and set(witness) == {'points', 'edges'}, 'witness fields')
    pts = []
    for p in witness['points']:
        need(type(p) is list and len(p) == 2, 'point'); pts.append([QF([_rat(x) for x in c], a, b) for c in p])
    n = len(pts); need(2 <= n <= 2000, 'point count')
    for u, v in witness['edges']:
        need(0 <= u < n and 0 <= v < n and u != v, 'edge'); budget.use(8)
        dx, dy = pts[u][0] - pts[v][0], pts[u][1] - pts[v][1]
        need((dx * dx + dy * dy).is_one(), 'an edge is not of length 1')
    _, adj = graph_of(dict(n=n, edges=witness['edges']), budget)
    need(chromatic_number(n, adj, budget) >= k, 'the graph is colorable with fewer colors')
    return dict(points=n, colors=k)


def _polygon(vs):
    need(type(vs) is list and 3 <= len(vs) <= 200, 'polygon'); return [_pt(v) for v in vs]


@family('config_q', 'mahler_polygon', 'value',
        'For the convex polygon (vertices in order, the origin inside): its area times the area of its polar body, '
        'exactly (Mahler conjectured the minimum over centrally symmetric bodies is attained by the square: 8 in the '
        'plane).')
def fam_mahler_polygon(params, budget):
    need(set(params) == {'vertices'}, 'polygon fields'); P = _polygon(params['vertices'])
    def area(poly): return abs(sum(p[0] * q[1] - q[0] * p[1] for p, q in zip(poly, poly[1:] + poly[:1]))) / 2
    for p, q in zip(P, P[1:] + P[:1]): need(p[0] * q[1] - q[0] * p[1] > 0, 'counterclockwise with the origin inside')
    # the polar body's vertices are the normals n with n . x = 1 on each edge
    polar = []
    for p, q in zip(P, P[1:] + P[:1]):
        det = p[0] * q[1] - p[1] * q[0]
        polar.append(((q[1] - p[1]) / det, (p[0] - q[0]) / det)); budget.use()
    v = area(P) * area(polar)
    return [v.numerator, v.denominator]


@family('config_q', 'illumination', 'witness',
        'The witness directions illuminate every vertex of the convex polygon (each vertex has a direction pointing '
        'strictly into the polygon across both its edges), so they illuminate its whole boundary: the illumination '
        'number, equal to its Hadwiger covering number, is at most their count.')
def fam_illumination(params, witness, budget):
    need(set(params) == {'vertices', 'count'}, 'illumination fields'); P = _polygon(params['vertices'])
    k = integer(params['count'], 1, 16)
    need(type(witness) is list and len(witness) <= k, 'direction count'); D = [_pt(d) for d in witness]
    n = len(P)
    for i in range(n):
        a, b, c = P[i - 1], P[i], P[(i + 1) % n]
        # inward normals of the two edges at b (counterclockwise polygon): rotate edge vectors left
        n1 = (-(b[1] - a[1]), b[0] - a[0]); n2 = (-(c[1] - b[1]), c[0] - b[0])
        need(any(d[0] * n1[0] + d[1] * n1[1] > 0 and d[0] * n2[0] + d[1] * n2[1] > 0 for d in D),
             'vertex ' + str(i) + ' is not illuminated')
        budget.use(len(D))
    return dict(directions=len(D))


@family('config_q', 'borsuk', 'witness',
        'The witness splits the listed points of R^d into d + 1 parts, each of diameter strictly smaller than the whole '
        'set\'s (squared distances, exact).')
def fam_borsuk(params, witness, budget):
    need(set(params) == {'points'}, 'Borsuk fields'); pts = params['points']
    need(type(pts) is list and 2 <= len(pts) <= 2000, 'points'); d = len(pts[0]); P = [_pt(p, d) for p in pts]
    diam = max(_d2(a, b) for a, b in combinations(P, 2)); budget.use(len(P) ** 2)
    need(type(witness) is list and len(witness) == len(P) and all(type(x) is int and 0 <= x <= d for x in witness), 'parts')
    for part in range(d + 1):
        S = [P[i] for i in range(len(P)) if witness[i] == part]
        need(all(_d2(a, b) < diam for a, b in combinations(S, 2)), 'a part keeps the full diameter')
    return dict(dimension=d, points=len(P))


@family('config_q', 'packing', 'value',
        'For the lattice with the listed integer basis: the least squared norm of a nonzero vector whose coefficients '
        'lie in the box [-box, box] (a shortest vector when the box holds one), and the absolute determinant. Its '
        'packing density is then pi^(d/2) / Gamma(d/2 + 1) (sqrt(min) / 2)^d / det.')
def fam_packing(params, budget):
    need(set(params) == {'basis', 'box'}, 'lattice fields'); B = params['basis']; R = integer(params['box'], 1, 6)
    need(type(B) is list and 1 <= len(B) <= 8 and all(type(r) is list and len(r) == len(B) and all(type(x) is int for x in r)
                                                       for r in B), 'square integer basis')
    d = len(B); best = None
    for c in product(range(-R, R + 1), repeat=d):
        if not any(c): continue
        budget.use(d * d)
        v = [sum(c[i] * B[i][j] for i in range(d)) for j in range(d)]; n2 = sum(x * x for x in v)
        if best is None or n2 < best: best = n2
    M = [[Q(x) for x in r] for r in B]; det = Q(1)
    for i in range(d):
        piv = next(r for r in range(i, d) if M[r][i] != 0); M[i], M[piv] = M[piv], M[i]
        if piv != i: det = -det
        det *= M[i][i]
        for r in range(i + 1, d):
            f = M[r][i] / M[i][i]; M[r] = [a - f * b for a, b in zip(M[r], M[i])]
    return dict(min_norm2=best, det=abs(int(det)))


# ------------------------------------------------------------- finite-field Kakeya

@family('kakeya_q', 'kakeya_set', 'witness',
        'The witness is a set of points of F_q^n (q prime) containing a full line in every direction: a Kakeya set, '
        'with its size.')
def fam_kakeya(params, witness, budget):
    need(set(params) == {'q', 'n'}, 'Kakeya fields'); q, n = integer(params['q'], 2, 31), integer(params['n'], 2, 3)
    need(is_prime(q, budget), 'prime q')
    need(type(witness) is list and len(witness) <= q ** n, 'points')
    S = set()
    for p in witness:
        need(type(p) is list and len(p) == n and all(type(x) is int and 0 <= x < q for x in p), 'point'); S.add(tuple(p))
    dirs = [d for d in product(range(q), repeat=n) if any(d) and d[next(i for i in range(n) if d[i])] == 1]
    for d in dirs:
        found = False
        for b in S:
            budget.use(q)
            if all(tuple((b[i] + t * d[i]) % q for i in range(n)) in S for t in range(q)): found = True; break
        need(found, 'no line in direction ' + str(d))
    return dict(size=len(S), directions=len(dirs))


# ------------------------------------------------------------- groups

def _word(w, ngens):
    need(type(w) is list and all(type(x) is int and x != 0 and abs(x) <= ngens for x in w), 'word of generator indices')
    return w


def coset_enumerate(ngens, relators, limit, budget):
    """Todd-Coxeter (HLT) enumeration of the cosets of the trivial subgroup: the group order, or None past the limit."""
    cols = [g for i in range(1, ngens + 1) for g in (i, -i)]
    table = [{c: None for c in cols}]; live = [True]
    parent = [0]
    def find(c):
        while parent[c] != c: parent[c] = parent[parent[c]]; c = parent[c]
        return c
    def define(c, x):
        need(len(table) < limit, 'coset limit')
        d = len(table); table.append({g: None for g in cols}); live.append(True); parent.append(d)
        table[c][x] = d; table[d][-x] = c; budget.use(len(cols))
        return d
    queue = []
    def coincidence(a, b):
        queue.append((a, b))
        while queue:
            a, b = queue.pop(); a, b = find(a), find(b)
            if a == b: continue
            if a > b: a, b = b, a
            parent[b] = a; live[b] = False
            for x in cols:
                t = table[b][x]
                if t is None: continue
                table[b][x] = None
                if table[t].get(-x) == b: table[t][-x] = None
                ta = table[a][x]
                if ta is None: table[a][x] = t; table[t][-x] = a
                else: queue.append((ta, t))
    def scan_and_fill(c, w):
        budget.use(len(w))
        f, i, b, j = c, 0, c, len(w) - 1
        while True:
            while i <= j and table[f][w[i]] is not None: f = table[f][w[i]]; i += 1
            if i > j:
                if f != c: coincidence(f, c)
                return
            while j >= i and table[b][-w[j]] is not None: b = table[b][-w[j]]; j -= 1
            if j < i: coincidence(f, b); return
            if i == j:
                table[f][w[i]] = b; table[b][-w[i]] = f; return
            define(f, w[i])
    c = 0
    while c < len(table):
        if live[c] and find(c) == c:
            for r in relators:
                if not live[c] or find(c) != c: break
                scan_and_fill(c, r)
            if live[c] and find(c) == c:
                for x in cols:
                    if table[c][x] is None: define(c, x)
        c += 1
    return sum(1 for i in range(len(table)) if live[i] and find(i) == i)


@family('group_q', 'coset_order', 'value',
        'The order of the group with the listed generators and relators (words in generator indices, negative for '
        'inverses), by Todd-Coxeter coset enumeration of the trivial subgroup; null when the coset limit is reached.')
def fam_coset_order(params, budget):
    need(set(params) == {'ngens', 'relators', 'limit'}, 'presentation fields')
    k, lim = integer(params['ngens'], 1, 4), integer(params['limit'], 1, 200_000)
    rels = [_word(r, k) for r in params['relators']]
    try: return coset_enumerate(k, rels, lim, budget)
    except Invalid as exc:
        if 'coset limit' in str(exc): return None
        raise


def _reduce(w):
    out = []
    for x in w:
        if out and out[-1] == -x: out.pop()
        else: out.append(x)
    return out


def _cyc_reduce(w):
    w = _reduce(w)
    while len(w) >= 2 and w[0] == -w[-1]: w = w[1:-1]
    return w


@family('group_q', 'ac_trivial', 'witness',
        'The witness Andrews-Curtis moves (invert r_i, replace r_i by r_i r_j or r_i r_j^-1, conjugate r_i by a '
        'generator) take the balanced presentation to the trivial one: each relator a single generator.')
def fam_ac(params, witness, budget):
    need(set(params) == {'relators'}, 'AC fields'); rels = [list(_word(r, 2)) for r in params['relators']]
    need(len(rels) == 2, 'two relators on two generators')
    need(type(witness) is list and len(witness) <= 100_000, 'moves')
    for mv in witness:
        need(type(mv) is list and len(mv) >= 2, 'move'); kind, i = mv[0], mv[1]; need(i in (0, 1), 'relator index')
        budget.use(len(rels[0]) + len(rels[1]))
        if kind == 'inv': rels[i] = _reduce([-x for x in reversed(rels[i])])
        elif kind == 'mul': rels[i] = _reduce(rels[i] + rels[1 - i])
        elif kind == 'mulinv': rels[i] = _reduce(rels[i] + [-x for x in reversed(rels[1 - i])])
        elif kind == 'conj':
            g = mv[2]; need(type(g) is int and g in (1, -1, 2, -2), 'conjugating generator')
            rels[i] = _reduce([g] + rels[i] + [-g])
        else: raise Invalid('unknown move')
        need(len(rels[i]) <= 10_000, 'relator length bound')
    final = sorted(abs(x) for r in rels for x in _cyc_reduce(r))
    need(all(len(_cyc_reduce(r)) == 1 for r in rels) and final == [1, 2], 'not the trivial presentation')
    return dict(moves=len(witness))


# ------------------------------------------------------------- knots

@family('knot_q', 'jones', 'value',
        'The Jones polynomial of the knot given by its planar diagram code (crossings [a, b, c, d] of arc labels), from '
        'the Kauffman bracket state sum and the writhe: coefficients from the lowest power of t, with that power.')
def fam_jones(params, budget):
    need(set(params) == {'pd'}, 'knot fields'); pd = params['pd']
    need(type(pd) is list and 2 <= len(pd) <= 14 and all(type(x) is list and len(x) == 4 for x in pd), 'crossings')
    m = 2 * len(pd); labels = [a for x in pd for a in x]
    need(all(type(a) is int for a in labels) and sorted(labels) == sorted(list(range(1, m + 1)) * 2),
         'every arc 1..2n appears exactly twice')
    need(all(c == a % m + 1 and (b - d) % m in (1, m - 1) for a, b, c, d in pd),
         'each crossing lists the incoming under-arc first, counterclockwise, with consecutive arcs')
    arcs = sorted(set(labels))
    # bracket in A: states smooth each crossing [a, b, c, d] as A (a-b, c-d) or A^-1 (a-d, b-c)
    poly = {}
    for state in product((0, 1), repeat=len(pd)):
        budget.use(len(pd))
        parent = {a: a for a in arcs}
        def find(x):
            while parent[x] != x: parent[x] = parent[parent[x]]; x = parent[x]
            return x
        for (a, b, c, d), s in zip(pd, state):
            pairs = ((a, b), (c, d)) if s == 0 else ((a, d), (b, c))
            for u, v in pairs: parent[find(u)] = find(v)
        loops = len({find(a) for a in arcs}); na = state.count(0); nb = len(pd) - na
        # A^(na - nb) (-A^2 - A^-2)^(loops - 1)
        term = {na - nb: 1}
        for _ in range(loops - 1):
            nxt = {}
            for e, c in term.items():
                nxt[e + 2] = nxt.get(e + 2, 0) - c; nxt[e - 2] = nxt.get(e - 2, 0) - c
            term = nxt
        for e, c in term.items(): poly[e] = poly.get(e, 0) + c
    poly = {e: c for e, c in poly.items() if c}
    # writhe: [a, b, c, d] (under-strand a -> c) is positive when the over-strand runs d -> b, i.e. b = d + 1 (mod 2n)
    w = sum(1 if (b - d) % m == 1 else -1 for a, b, c, d in pd)
    # V(t) = (-A^3)^(-w) <K> with A = t^(-1/4)
    sign = -1 if w % 2 else 1
    V = {}
    for e, c in poly.items():
        k = e - 3 * w  # power of A
        need(k % 4 == 0, 'the bracket is not a polynomial in t for a knot')
        V[-k // 4] = V.get(-k // 4, 0) + sign * c
    lo, hi = min(V), max(V)
    return dict(lowest_power=lo, coefficients=[V.get(i, 0) for i in range(lo, hi + 1)])


@family('knot_q', 'inscribed_square', 'witness',
        'The witness gives four points on the boundary of the polygon (rational vertices) that are the corners of a '
        'square with positive side, in order.')
def fam_inscribed_square(params, witness, budget):
    need(set(params) == {'vertices'}, 'polygon fields'); P = _polygon(params['vertices'])
    need(type(witness) is list and len(witness) == 4, 'four corners'); S = [_pt(p) for p in witness]
    def on_boundary(x):
        for a, b in zip(P, P[1:] + P[:1]):
            if _area2(a, b, x) == 0 and min(a[0], b[0]) <= x[0] <= max(a[0], b[0]) and min(a[1], b[1]) <= x[1] <= max(a[1], b[1]):
                return True
        return False
    need(all(on_boundary(x) for x in S), 'a corner is not on the boundary')
    for i in range(4):
        a, b, c = S[i], S[(i + 1) % 4], S[(i + 2) % 4]
        need((b[0] - a[0], b[1] - a[1]) == (-(c[1] - b[1]), c[0] - b[0]) or (b[0] - a[0], b[1] - a[1]) == (c[1] - b[1], -(c[0] - b[0])),
             'not a square')
    need(S[0] != S[1], 'a degenerate square')
    budget.use(len(P) * 4)
    return dict(side2=str(_d2(S[0], S[1])))


# ------------------------------------------------------------- polynomial algebra

def _mpoly(p, nvars):
    """A polynomial as {exponent tuple: rational}: from [[coefficient, [exponents]], ...]."""
    need(type(p) is list and len(p) <= 400, 'polynomial terms'); out = {}
    for c, e in p:
        need(type(e) is list and len(e) == nvars and all(type(x) is int and 0 <= x <= 60 for x in e), 'exponents')
        k = tuple(e); out[k] = out.get(k, Q(0)) + _rat(c)
    return {k: v for k, v in out.items() if v}


def _padd(a, b):
    out = dict(a)
    for k, v in b.items():
        out[k] = out.get(k, Q(0)) + v
        if not out[k]: del out[k]
    return out


def _pmul(a, b, budget):
    out = {}
    for k1, v1 in a.items():
        for k2, v2 in b.items():
            k = tuple(x + y for x, y in zip(k1, k2)); out[k] = out.get(k, Q(0)) + v1 * v2
    budget.use(len(a) * len(b))
    return {k: v for k, v in out.items() if v}


def _compose(f, G, budget):
    """f(G_1, ..., G_n) for a polynomial f and a list of polynomials G."""
    n = len(G); out = {}; cache = {}
    def power(i, e):
        if (i, e) not in cache:
            r = {(0,) * n: Q(1)}
            for _ in range(e): r = _pmul(r, G[i], budget); need(len(r) <= 20_000, 'composition size')
            cache[(i, e)] = r
        return cache[(i, e)]
    for k, c in f.items():
        term = {(0,) * n: c}
        for i, e in enumerate(k):
            if e: term = _pmul(term, power(i, e), budget)
        out = _padd(out, term)
    return out


@family('algebra_q', 'polynomial_inverse', 'witness',
        'The witness polynomial map G is a two-sided inverse of the listed polynomial map F of the plane: F(G(x, y)) = '
        '(x, y) and G(F(x, y)) = (x, y) as polynomials (so F is invertible, and its Jacobian determinant is a nonzero '
        'constant).')
def fam_poly_inverse(params, witness, budget):
    need(set(params) == {'F'}, 'map fields'); F = [_mpoly(f, 2) for f in params['F']]; need(len(F) == 2, 'two components')
    need(type(witness) is list and len(witness) == 2, 'two components'); G = [_mpoly(g, 2) for g in witness]
    X, Y = {(1, 0): Q(1)}, {(0, 1): Q(1)}
    need([_compose(f, G, budget) for f in F] == [X, Y], 'F(G) is not the identity')
    need([_compose(g, F, budget) for g in G] == [X, Y], 'G(F) is not the identity')
    return dict(degree=max(sum(k) for f in F for k in f))


def _upoly_mod(p, q):
    """An integer polynomial (lowest degree first) reduced mod q, trimmed."""
    r = [c % q for c in p]
    while len(r) > 1 and r[-1] == 0: r.pop()
    return r


def _pmod_divmod(a, b, q):
    a = list(a); inv = pow(b[-1], -1, q); out = [0] * max(1, len(a) - len(b) + 1)
    while len(a) >= len(b) and any(a):
        c = a[-1] * inv % q; s = len(a) - len(b); out[s] = c
        for i, x in enumerate(b): a[s + i] = (a[s + i] - c * x) % q
        while a and a[-1] == 0: a.pop()
    return out, a or [0]


def _pmod_gcd(a, b, q):
    a, b = _upoly_mod(a, q), _upoly_mod(b, q)
    while any(b):
        _, r = _pmod_divmod(a, b, q); a, b = b, _upoly_mod(r, q)
    return a


def _pmod_mul(a, b, q):
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        for j, y in enumerate(b): out[i + j] = (out[i + j] + x * y) % q
    return out


def _pmod_powmod(base, e, m, q):
    result = [1]; base = _pmod_divmod(base, m, q)[1]
    while e:
        if e & 1: result = _pmod_divmod(_pmod_mul(result, base, q), m, q)[1]
        base = _pmod_divmod(_pmod_mul(base, base, q), m, q)[1]; e >>= 1
    return result


def factor_degrees_mod(f, q):
    """The degrees of the irreducible factors of a squarefree polynomial mod a prime q (distinct-degree factorization)."""
    f = _upoly_mod(f, q); inv = pow(f[-1], -1, q); f = [c * inv % q for c in f]
    degs = []; x = [0, 1]; h = x; d = 0
    while len(f) - 1 >= 2 * (d + 1):
        d += 1; h = _pmod_powmod(h, q, f, q)
        diff = list(h) + [0] * (2 - len(h)); diff[1] = (diff[1] - 1) % q
        g = _pmod_gcd(f, _upoly_mod(diff, q), q)
        if len(g) > 1:
            degs += [d] * ((len(g) - 1) // d); f = _pmod_divmod(f, g, q)[0]; h = _pmod_divmod(h, f, q)[1] if len(f) > 1 else [0]
    if len(f) > 1: degs.append(len(f) - 1)
    return sorted(degs)


def _disc(f):
    """The discriminant of an integer polynomial (lowest degree first), via the resultant with its derivative."""
    df = [i * c for i, c in enumerate(f)][1:]
    n = len(f) - 1
    R = _resultant([Q(c) for c in f], [Q(c) for c in df])
    return int(R * (-1) ** (n * (n - 1) // 2) / f[-1])


def _resultant(a, b):
    """Resultant of two polynomials (lowest degree first) by the Euclidean algorithm over Q."""
    a, b = list(a), list(b); res = Q(1)
    while True:
        while a and a[-1] == 0: a.pop()
        while b and b[-1] == 0: b.pop()
        if len(b) == 1: return res * b[0] ** (len(a) - 1)
        if not b: return Q(0)
        da, db = len(a) - 1, len(b) - 1
        r = list(a)
        while len(r) >= len(b) and any(r):
            c = r[-1] / b[-1]; s = len(r) - len(b)
            for i, x in enumerate(b): r[s + i] -= c * x
            r.pop()
            while r and r[-1] == 0: r.pop()
        dr = len(r) - 1 if r else -1
        if dr < 0: return Q(0)
        res *= (-1) ** (da * db) * b[-1] ** (da - dr)
        a, b = b, r


def _rational_roots(g):
    """The integer roots of a monic integer polynomial (lowest degree first)."""
    out = set(); c0 = abs(g[0])
    if c0 == 0: out.add(0); return out
    for d in range(1, isqrt(c0) + 1):
        if c0 % d == 0:
            for r in (d, -d, c0 // d, -(c0 // d)):
                if sum(c * r ** i for i, c in enumerate(g)) == 0: out.add(r)
    return out


def _irreducible(f, budget):
    """Whether a monic integer polynomial of degree 2..5 is irreducible over Q: no root and no monic quadratic factor
    (Gauss: a factorization over Q gives one over Z with monic factors)."""
    n = len(f) - 1
    if _rational_roots(f): return False
    if n < 4: return True
    B = 1 + max(abs(c) for c in f[:-1])  # Cauchy: every root has |z| < B
    for u in range(-2 * B, 2 * B + 1):
        for v in range(-B * B, B * B + 1):
            if v == 0 or f[0] % v: continue
            budget.use(n)
            r = [Q(c) for c in f]
            q = [Q(v), Q(u), Q(1)]
            while len(r) >= 3:
                c = r[-1]; sh = len(r) - 3
                for i in range(3): r[sh + i] -= c * q[i]
                r.pop()
            if not any(r): return False
    return True


def _q_square(x):
    x = Q(x)
    return x >= 0 and isqrt(x.numerator) ** 2 == x.numerator and isqrt(x.denominator) ** 2 == x.denominator


@family('algebra_q', 'galois_group', 'value',
        'The Galois group over Q of the listed monic irreducible integer polynomial of degree 3, 4 or 5 (irreducibility '
        'checked exactly). Degree 3: the discriminant decides S3 or C3. Degree 4: the resolvent cubic and the '
        'Kappe-Warren test decide S4, A4, D4, C4 or V4. Degree 5: a Frobenius transposition at a prime up to p_max gives '
        'S5; a square discriminant with a 3-cycle gives A5; otherwise null (the solvable groups are not decided here).')
def fam_galois(params, budget):
    need(set(params) == {'poly', 'p_max'}, 'Galois fields'); f = params['poly']; P = integer(params['p_max'], 5, 2000)
    need(type(f) is list and 4 <= len(f) <= 6 and all(type(c) is int and abs(c) <= 10 ** 6 for c in f) and f[-1] == 1,
         'monic of degree 3 to 5')
    n = len(f) - 1; D = _disc(f); need(D != 0, 'repeated roots')
    need(_irreducible(f, budget), 'the polynomial is reducible')
    square = _q_square(D)
    if n == 3: return 'C3' if square else 'S3'
    if n == 4:
        e_, d_, c_, b_ = f[0], f[1], f[2], f[3]
        cub = [-(b_ * b_ * e_ - 4 * c_ * e_ + d_ * d_), b_ * d_ - 4 * e_, -c_, 1]
        rr = _rational_roots(cub)
        if not rr: return 'A4' if square else 'S4'
        if len(rr) == 3: return 'V4'
        t = next(iter(rr))
        return 'C4' if _q_square((t * t - 4 * e_) * D) and _q_square((b_ * b_ - 4 * (c_ - t)) * D) else 'D4'
    types = set()
    for p in range(3, P + 1):
        if not is_prime(p, budget) or D % p == 0: continue
        budget.use(n * n * p.bit_length()); types.add(tuple(factor_degrees_mod(f, p)))
    if (1, 1, 1, 2) in types: return 'S5'
    if square and (1, 1, 3) in types: return 'A5'
    return None


@family('algebra_q', 'tensor', 'witness',
        'The witness lists r rank-one terms a_i (x) b_i (x) c_i (integer n x m, m x p and p x n matrices, row major) '
        'whose sum is the matrix multiplication tensor <n, m, p>: an algorithm with r multiplications, so its rank is '
        'at most r (and omega <= 3 log r / log(n m p) when n = m = p).')
def fam_tensor(params, witness, budget):
    need(set(params) == {'n', 'm', 'p', 'rank'}, 'tensor fields')
    n, m, p = (integer(params[k], 1, 6) for k in ('n', 'm', 'p')); r = integer(params['rank'], 1, 300)
    need(type(witness) is list and len(witness) <= r, 'at most rank terms')
    T = {}
    for term in witness:
        need(type(term) is list and len(term) == 3, 'three factors'); A, B, C = term
        need(len(A) == n * m and len(B) == m * p and len(C) == p * n and all(type(x) is int for x in A + B + C), 'factor sizes')
        for i, a in enumerate(A):
            if not a: continue
            for j, b in enumerate(B):
                if not b: continue
                for k, c in enumerate(C):
                    if c: T[(i, j, k)] = T.get((i, j, k), 0) + a * b * c
        budget.use(len(A) * len(B))
    # <n, m, p>: A[i][j] B[j][k] contributes to C[i][k]; the dual index of C is (k, i)
    target = {}
    for i in range(n):
        for j in range(m):
            for k in range(p): target[(i * m + j, j * p + k, k * n + i)] = 1
    need({key: v for key, v in T.items() if v} == target, 'the terms do not sum to the matrix multiplication tensor')
    return dict(rank=len(witness))


@family('algebra_q', 'casas_alvero', 'value',
        'Among monic integer polynomials of the given degree with other coefficients of size at most h_max: those that '
        'share a root with each of their first degree - 1 derivatives without being (x - a)^degree (counterexamples to '
        'Casas-Alvero); expected none.')
def fam_casas_alvero(params, budget):
    need(set(params) == {'degree', 'h_max'}, 'Casas-Alvero fields')
    d, H = integer(params['degree'], 2, 8), integer(params['h_max'], 1, 4)
    need((2 * H + 1) ** d <= 400_000, 'enumeration bound')
    out = []
    def gcd_deg(a, b):
        a = [Q(x) for x in a]; b = [Q(x) for x in b]
        while any(b):
            while b and b[-1] == 0: b.pop()
            r = list(a)
            while len(r) >= len(b) and any(r):
                c = r[-1] / b[-1]; s = len(r) - len(b)
                for i, x in enumerate(b): r[s + i] -= c * x
                r.pop()
                while r and r[-1] == 0: r.pop()
            a, b = b, r
        return len(a) - 1
    for cs in product(range(-H, H + 1), repeat=d):
        f = list(cs) + [1]; budget.use(d * d)
        g = f; ok = True
        for k in range(1, d):
            g = [i * c for i, c in enumerate(g)][1:]
            if gcd_deg(f, g) < 1: ok = False; break
        if not ok: continue
        # (x - a)^d: then c_(d-1) = -d a and the polynomial equals (x + c_(d-1)/d)^d
        a = Q(-f[d - 1], d)
        expand = [comb(d, i) * (-a) ** (d - i) for i in range(d + 1)]
        if [Q(c) for c in f] != expand: out.append(f)
    return out


# ------------------------------------------------------------- curves over finite fields

@family('variety_q', 'elliptic_ap', 'value',
        'For E: y^2 = x^3 + a x + b and each prime 3 < p <= p_max not dividing its discriminant: a_p = p + 1 - #E(F_p) '
        '(projective points), with the Hasse bound a_p^2 <= 4p checked; and the product of #E(F_p)/p over these primes '
        'as decimal bounds (Birch and Swinnerton-Dyer\'s original numerical evidence).')
def fam_elliptic_ap(params, budget):
    need(set(params) == {'a', 'b', 'p_max'}, 'curve fields')
    a, b, P = integer(params['a'], -10 ** 6, 10 ** 6), integer(params['b'], -10 ** 6, 10 ** 6), integer(params['p_max'], 5, 5000)
    disc = -16 * (4 * a ** 3 + 27 * b * b); need(disc != 0, 'singular curve')
    aps = {}; lo, hi = Q(1), Q(1)
    for p in range(5, P + 1):
        if not is_prime(p, budget) or disc % p == 0: continue
        budget.use(p)
        s = sum(jacobi((x * x * x + a * x + b) % p, p) for x in range(p))
        ap = -s; need(ap * ap <= 4 * p, 'Hasse bound fails'); aps[str(p)] = ap
        lo *= Q(p + 1 - ap, p)
    v = lo
    return dict(ap=aps, product=[v.numerator.bit_length() - v.denominator.bit_length(), str(round(float(v), 6))])


@family('variety_q', 'rational_points', 'witness',
        'The witness lists rational points (x, y) on y^2 = x^3 + a x + b, each checked exactly.')
def fam_rational_points(params, witness, budget):
    need(set(params) == {'a', 'b'}, 'curve fields'); a, b = integer(params['a']), integer(params['b'])
    need(type(witness) is list and 1 <= len(witness) <= 1000, 'points')
    for pt in witness:
        x, y = _pt(pt); budget.use(); need(y * y == x ** 3 + a * x + b, 'a point is not on the curve')
    return dict(points=len(witness))


@family('variety_q', 'point_count', 'value',
        'The number of points over F_p of the projective hypersurface given by a homogeneous integer polynomial in '
        'n + 1 variables (terms [coefficient, [exponents]]), by exhaustive count.')
def fam_point_count(params, budget):
    need(set(params) == {'poly', 'nvars', 'p'}, 'point count fields')
    k, p = integer(params['nvars'], 2, 4), integer(params['p'], 2, 200); need(is_prime(p, budget), 'prime p')
    need(p ** k <= 5_000_000, 'enumeration bound'); f = _mpoly(params['poly'], k)
    degs = {sum(e) for e in f}; need(len(degs) == 1, 'homogeneous')
    count = 0
    for v in product(range(p), repeat=k):
        if not any(v): continue
        # one representative per line: first nonzero coordinate 1
        if v[next(i for i in range(k) if v[i])] != 1: continue
        budget.use(len(f))
        if sum(int(c) * _prod(x ** e for x, e in zip(v, ex)) for ex, c in f.items()) % p == 0: count += 1
    return count


def _prod(xs):
    out = 1
    for x in xs: out *= x
    return out
